<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<NoWarn>$(NoWarn);NU1701</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="FontAwesome.WPF" Version="4.7.0.9" />
		<PackageReference Include="GMap.NET.Core" Version="2.1.7" />
		<PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
		<PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc5" />
		<PackageReference Include="MaterialDesignColors" Version="5.3.2" />
		<PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
		<PackageReference Include="MaterialDesignThemes.Wpf" Version="1.0.1" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0-preview1.26124.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3965-prerelease" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
		<PackageReference Include="System.Device.Location.Portable" Version="1.0.0" />
	</ItemGroup>

</Project>